---
- name: Install apt-transport-https
  ansible.builtin.apt:
    name: apt-transport-https
    state: present
    update_cache: yes
    cache_valid_time: 900
  become: yes

- name: Add signing key
  ansible.builtin.apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present
  become: yes

- name: Add apt reposditory
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://storage.googleapis.com/download.dartlang.org/linux/debian stable main"
    state: present
    update_cache: yes
  become: yes

- name: Install dart
  ansible.builtin.apt:
    name: dart
    state: present
    cache_valid_time: 900
  become: yes
